### ISSUE TITLE
Support for property values autocomplete

### ISSUE THREAD

**Issue by cooolbasha** [billymoon/Stylus#31]
![image](https://cloud.githubusercontent.com/assets/1131747/3084847/e5e8217c-e500-11e3-8679-e6646fd3a4db.png)

I have the snippets too installed. should I uninstall and reinstall from wbond again. as I don't get any drop down for eg..float should drop down as right,left,etc...

**Comment by andremacola** [comment]
Using LESS syntax for auto complete to work.. but Stylus colors is lost

**Comment by utsavdevsharma** [comment]
Anyone landing on this thread to get autocomplete working, this works great for me - https://github.com/lnikell/stylus-clean-completions

**Comment by grassator** [comment]
@utsavdevsharma Thank you. With your comment I consider this thread closed.
