### ISSUE TITLE
Option to include semicolons and colons when using Emmet

### ISSUE THREAD

**Issue by aaronbushnell** [billymoon/Stylus#53]
Is there a way to enable semicolons and colons when expanding with Emmet. For example, typing `m0` and hitting tab to generate: `margin: 0;` not `margin 0`

**Comment by grassator** [comment]
You can create `Emmet.sublime-settings` file in your `User` folder in sublime packages.

```json
{
	"preferences": {
		"stylus.propertyEnd": ";",
		"stylus.valueSeparator": ": "
	}
}
```

**Comment by aaronbushnell** [comment]
Ah, didn't realize this was an Emmet setting. Thanks for the quick reply!

**Comment by Leolik** [comment]
how do this, but for WebStorm?
