### ISSUE TITLE
Is it possible to change (even at a user-settings-level) some autocomplete behaviour.

### ISSUE THREAD

**Issue by krispii** [billymoon/Stylus#59]
First off, thanks for creating and maintaining this.
One issue/feature I'd love to see is the ability to change the autocomplete to reflect one of Stylus' advantages, that is not having to use the colon.

However, when sublime currently suggests a property name and I select it (hitting enter/return/whatever) a colon is inserted afterward. Since this is extraneous in Stylus, is there an option to do away with it as a personal default?

Many thanks.

**Comment by herrbischoff** [comment]
I very much second this. Since Stylus has become my sole CSS language of choice, this would greatly streamline my work.

**Comment by grassator** [comment]
Which package are using for autocomplete? My clean installation of just Sublime Text and Stylus doesn't provide one.

**Comment by herrbischoff** [comment]
@grassator: I'm using the standard CSS3 package and Emmett. I tried the Stylus autocomplete package but that one inserts the colons as well. Having looked into the source code, I'm already thinking about just changing the autocomplete targets to colon-less.

**Comment by grassator** [comment]
Ok, I think I'm missing something. In a completely fresh install of Sublime Text 3 I added following packages:
![image](https://cloud.githubusercontent.com/assets/317518/7190222/bbc0bb46-e484-11e4-9d9f-1431053145b8.png)

And disabled default CSS packages (as recommended by CSS3). I still don't have any dropdown completions.

As far as tab expansions like `dib` -> `display inline-block` it works perfectly.

**Comment by herrbischoff** [comment]
Interesting. I tried this on a completely empty Stylus file and it works as you described. Must be another plugin interfering within the project scope. I'm looking into that now.

**Comment by herrbischoff** [comment]
Alright, it appears it was my setup that was at fault. After disabling the All Autocomplete package (d'oh!) and setting `"auto_complete": false` (just for good measure) I have no problematic dropdowns anymore and the tab completions work as expected. Nice! Thanks for your testing, I feel a little bit like a noob now.

**Comment by grassator** [comment]
@krispii could you also please check your list of packages and if problem still not solved. Otherwise I will close this ticket in a couple of days.

**Comment by krispii** [comment]
Removing package CSS Completions remedied the issue. 

Good catch and thanks!
