### ISSUE TITLE
Cannot use attribute "for" in selector 

### ISSUE THREAD

**Issue by mborman** [billymoon/Stylus#60]
Maybe I missed something... I am new to stylus.

But a css selector like this will break the compiler

    label[for="firstname"]
      clear both

using normal css does not help

    label[for="firstname"] {
      clear: both;
    }

I am assuming the compiler thinks the "for" is the start of a loop when in fact it is a valid attribute name of the label HTML tag.

**Comment by billymoon** [comment]
@mborman this is the package for the Sublime Text plugin to support the Stylus language - I raised your issue in the main Stylus project, and will close this ticket.
