### ISSUE TITLE
Autocomplete not working?

### ISSUE THREAD

**Issue by Orbyt** [billymoon/Stylus#62]
It seems that the autocomplete has to "learn" the property values everytime i start a new file. Eg: starting to type `displ` does not bring up the option to autocomplete to `display`, BUT it will autocomplete if I use the propery again. How can I get autocomplete working?

**Comment by grassator** [comment]
Sublime and by extension this package uses autocomplete based on already present symbols (words) in the document. So the behavior you described is natural and not an issue.

There is already an open feature request (https://github.com/billymoon/Stylus/issues/31) for more IDE-like autocomplete, where pull requests are welcome, but it's doubtful that I will work on that myself.

**Comment by utsavdevsharma** [comment]
Anyone landing on this thread to get autocomplete working, this works great for me - https://github.com/lnikell/stylus-clean-completions
