### ISSUE TITLE
`fieldgroup` isn't picked up as an HTML element

### ISSUE THREAD

**Issue by nathanhornby** [billymoon/Stylus#63]
I was going to slip this in myself but I don't have any experience with Sublime plugins so thought it best to just report it.

`fieldgroup` isn't visually flagged as an HTML element:

![screen shot 2015-06-17 at 11 16 35](https://cloud.githubusercontent.com/assets/1975168/8204697/5a04a712-14e2-11e5-8790-910b83efa6ec.png)

**Comment by grassator** [comment]
This is correct behavior, because `fieldgroup` it's not a valid tag. What you probably want is `fieldset`.
https://developer.mozilla.org/en/docs/Web/HTML/Element

**Comment by nathanhornby** [comment]
Doh!
