### ISSUE TITLE
@media queries without brackets {} breaks syntax highlighting

### ISSUE THREAD

**Issue by hworld** [billymoon/Stylus#68]
Syntax definition for media query blocks without brackets fails. Example:

```stylus
@media screen and (max-width: 500px)
    a
        color: #fff
```

With the brackets `{}` around around the media block it works.

Just wanted to say great work on the syntax file! It's pretty amazing how much it supports of Stylus's crazy syntax.

**Comment by grassator** [comment]
Can you please clarify what doesn't work and maybe make a screenshot? Looks the same to me with or without braces:

![media queries](https://cloud.githubusercontent.com/assets/317518/11284306/50c03788-8f09-11e5-8708-37bade1b19f4.png)

**Comment by hworld** [comment]
Ah, it must be a weird issue with Visual Studio Code, then. Will close it out since it's probably just Code failing at parsing the rules somehow.

**Comment by hworld** [comment]
Hey, I figured out what it is... I use $vars for all my media queries. I believe that's what actually breaks it for me:

```stylus
@media $media-sm-up
  a
    color: #fff
```

**Comment by grassator** [comment]
Works for me as well...
![media-with-var](https://cloud.githubusercontent.com/assets/317518/11451820/4de7273a-95d3-11e5-8f1b-50bb5004f734.png)

**Comment by hworld** [comment]
Bah, it's gotta just be VS Code, then. It seems to highlight everything correctly except for this one case with variables with a `$` after the `@media`. Probably more of an issue for them, then.

Sorry for wasting your time, and thanks for bearing with me!
