### ISSUE TITLE
New line with enter does not work inside <style lang=“stylus”> tag

### ISSUE THREAD

**Issue by PrimozRome** [billymoon/Stylus#70]
Enter key does not work inside sublime text 3 for new line when I am with the cursor at the end of the line inside style lang="stylus" tag...

     <style lang="stylus">
         body
             background: #eee
     </style>

It works though if the stye tag is used without lang="stylus" or if I remove the Stylus package all together. But the syntax highlighting is not working inside < style lang="stylus" > tag ... which sucks. 

Any idea what to do?

**Comment by grassator** [comment]
For the embedded language usually the problem lies in the original package. Which Syntax do you use for this? The code you provide results in CSS syntax for when embedded in HTML. So I need additional details, but might not be able to help depending on the context.

**Comment by PrimozRome** [comment]
Not sure if I understand your question regarding the syntax use...?

My solution now is that I use shift+enter which will put me into the new line normally. If I remove the Stylus plugin then it works normally, but with stylus plugin I now just use shift+enter. Maybe it's a feature?

**Comment by grassator** [comment]
My question is what type of file do you enter `<style lang="stylus">` into and what other packages do you have installed because for me inside an HTML file that doesn't trigger the stylus syntax highlighting

**Comment by PrimozRome** [comment]
It's a .vue - Vue JS file... I have couple of packages installed. Standard frontend JS/HTML/CSS workflow packages...

**Comment by grassator** [comment]
There were already a few issue with Vue.js integration and I would say it's the issue on that end and it's reported as closed:
https://github.com/vuejs/vue-syntax-highlight/issues/8

**Comment by jpokrzyk** [comment]
The SASS sublime plugin works fine in this scenario. Even when I just use it on stylus code in the .vue files. So I would say the fix probably has to happen in this code somewhere. 

I spent a couple of hours on this and then got frustrated and gave up. But a lot of that was just learning about sublime plugins and the textmate format. I might take another crack at it at some point.

**Comment by grassator** [comment]
I've tried to replicate the issue by testing separately Stylus with:
* Vue Syntax Highlight
* Vuejs Complete Package

Both seems be working for me. Could you please try with the latest versions of both packages. If the issue persists please provide exact steps to replicate the issue and used versions of both sublime and packages.

**Comment by jpokrzyk** [comment]
Yep. Hang on. I'll start from scratch and write it up. Thanks for looking into this!

You definitely won't be able to reproduce with Vuejs Synxtax highlight because of:  https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.YAML-tmLanguage#L80

The `source.vue-stylus.embedded.html` instead of `source.vue-stylus.embedded.html` means that's not using your stylus package anymore (at least that's my understanding).

**Comment by jpokrzyk** [comment]
1. Uninstall the vue complete package. Let's just work with the vue syntax highlight for now. So install that one if it's not already.
2. Grab this gist: https://gist.github.com/jpokrzyk/e374b05c4bd5eab5f8c54a8c07041770 or test.vue file from: https://drive.google.com/open?id=0B4xqCaDmiMftR2tzWVNNZ0RVTm8
3. Do a crtl + / on one of the stylus lines. It should do a html comment (confirming it's not using your plugin). 
![image](https://cloud.githubusercontent.com/assets/4333958/14189416/1d9422f6-f75b-11e5-80d1-b728bd7e241d.png)
4. Now uncomment.
5. Now grab `Vue Syntax Highlight.zip` from https://drive.google.com/open?id=0B4xqCaDmiMftVmhlSm1oejdEWjQ and unzip into your sublime prefs directory. For me that's `C:\Users\Jon\AppData\Roaming\Sublime Text 3\Packages\Vue Syntax Highlight`
6. Now crtl +/ and comment/uncomment again and make sure you're getting stylus comments
![image](https://cloud.githubusercontent.com/assets/4333958/14189840/7ccf1f62-f75d-11e5-96eb-32fa1945bf29.png)
7. Now go to the end of line 8 when it's uncommented and try and do a newline with the enter key. Hopefully you're getting the same result and you're unable to get one without shift+enter
![image](https://cloud.githubusercontent.com/assets/4333958/14189878/ab9b1260-f75d-11e5-913d-48419f65ca65.png)

Github wouldn't let me attach zips. Here's the google drive folder with everything: https://drive.google.com/folderview?id=0B4xqCaDmiMftVHl5bGV3Rll2eWM&usp=sharing

Let me know if that works for you for reproducing.

**Comment by grassator** [comment]
@jpokrzyk Thanks for a thorough report. 

The problem turned out to be in the fact that in the `is_enabled` check for the command in Python I was checking the scope at the start of the document but when sublime dispatched the command it checked the scope under the cursor which resulted in this weird behaviour. This should be fixed now so you can checkout latest master to try it out before changes propagate to package control.

**Comment by jpokrzyk** [comment]
Nice! Yep that definitely did it. Thanks!
