### ISSUE TITLE
Proper built-in color functions highlighting

### ISSUE THREAD

**Issue by evenfrost** [billymoon/Stylus#71]
For functions like `hsla`, `hsl`, `rgba` and `rgb` Stylus [supports](http://stylus-lang.com/docs/bifs.html#hslacolor--hsla) the following syntax:
```stylus
body
  color hsla(#000, .5) // make it semi-transparent
  background rgb(#fff) // fwiw
```
Would be great if the package could properly highlight such cases as well.

**Comment by grassator** [comment]
@evenfrost Thanks for the report, should be fixed now
